name: Run tests and deploy automation functions
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install -r requirements-dev.txt
      - name: Populate .env file
        run: |
          echo "${{ secrets.BAM_ENV_FILE_CONTENTS }}" > ./.env
      - name: Run core tests
        run: |
          pip install .
          pytest -vv .
        working-directory: ./core
      - name: Run API tests
        run: |
          pip install ../core
          pip install -r requirements.txt
          pytest -vv .
        working-directory: ./app
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dev dependencies
      run: |
        pip install -r requirements-dev.txt
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - name: Populate .env file for functions
      run: |
        echo "${{ secrets.BAM_ENV_FILE_CONTENTS }}" > ./.env
    - name: Install doctl serverless plugin
      run: |
        doctl serverless install
    - name: Connect to DigitalOcean
      run: |
        doctl serverless connect
    - name: Deploy functions
      run: make deploy-functions
      working-directory: ./
