name: Deploy automation functions
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/test.yml

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v3
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - name: Populate .env file for functions
      run: |
        echo "${{ secrets.BAM_ENV_FILE_CONTENTS }}" > ./.env
    - name: Install doctl serverless plugin
      run: |
        doctl serverless install
    - name: Connect to DigitalOcean
      run: |
        doctl serverless connect
    - name: Deploy functions
      run: make deploy-functions
      working-directory: ./
