name: Nightly cron job

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Run the analysis in dry-run mode'
        required: true
        default: 'no'
  schedule:
    - cron: '0 4 * * *'  # Run every day at midnight ET

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Populate .env file, install dependencies and execute analysis
        run: |
          echo "${{ secrets.BAM_ENV_FILE_CONTENTS }}" > ./.env
          export $(xargs <.env)
          python -m pip install --upgrade pip wheel setuptools
          pip install ./core/
          if [ ${{ github.event.inputs.dry_run }} != "" ]; then
            python -m bam_core.functions.analyze_fulfilled_requests --dry-run ${{ github.event.inputs.dry_run }} 
          else 
            python -m bam_core.functions.analyze_fulfilled_requests --dry-run no
          fi
