name: Run checks and tests
on:
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  check-core:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./core

    steps:
      - uses: actions/checkout@v3
      - uses: astral-sh/setup-uv@v10.1.0
        with:
          enable-cache: true
      - name: Populate .env file
        run: |
          echo "${{ secrets.BAM_ENV_FILE_CONTENTS }}" > ./.env
      - name: Install Python and dependencies
        run: |
          uv sync --locked --dev
      - name: Run linting and formatting checks
        run: |
          uv run ruff check .
          uv run ruff format --check .
      - name: Run type checks
        run: |
          uv run ty check .
      - name: Run tests
        run: |
          uv run pytest -vv .

  check-app:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app

    steps:
      - uses: actions/checkout@v3
      - uses: astral-sh/setup-uv@v10.1.0
        with:
          enable-cache: true
      - name: Populate .env file
        run: |
          echo "${{ secrets.BAM_ENV_FILE_CONTENTS }}" > ./.env
      - name: Install Python and dependencies
        run: |
          uv sync --locked --dev
      - name: Run linting and formatting checks
        run: |
          uv run ruff check .
          uv run ruff format --check .
      - name: Run type checks
        run: |
          uv run ty check .
      - name: Run tests
        run: |
          uv run pytest -vv .
