name: Run tests
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install -r requirements-dev.txt
      - name: Populate .env file
        run: |
          echo "${{ secrets.BAM_ENV_FILE_CONTENTS }}" | base64 -d > ./.env
      - name: Run core tests
        run: |
          pip install .
          pytest -vv .
        working-directory: ./core
      - name: Run API tests
        run: |
          pip install ../core
          pip install -r requirements.txt
          pytest -vv .
        working-directory: ./app
